# Site settings
title: Inuits jobs
email: info@inuits.eu
description: > # this means to ignore newlines until "baseurl:"
 Creative is a one page Bootstrap theme for creatives, small businesses, and other multipurpose uses.
 The theme includes a number of rich features and plugins that you can use as a great boilerplate for your next Jekyll project!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "inuitsjobs" # the base hostname & protocol for your site

twitter_username: Inuits
github_username:  Inuits

# Build settings
markdown: kramdown
